#ifndef GARAGE_DOOR_DOORSTATE_H
#define GARAGE_DOOR_DOORSTATE_H

//state for state machine
enum class DoorState {
    NOT_CALIBRATED, CALIBRATED, DOOR_OPENED, DOOR_CLOSED, DOOR_OPENING, DOOR_CLOSING, ERROR
};

enum class Error {
    NORMAL, STUCK
};

#endif //GARAGE_DOOR_DOORSTATE_H